name: myst-publish

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install mystmd
      run: |
        npm install -g mystmd

    - name: Build site
      run: |
        myst build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html